### ISSUE TITLE
Is there a problem with the Jason format in the dataset?

### ISSUE THREAD

**Issue by shaoyuyoung** [zfj1998/M3NSCT5#1]
您好，
请问您的项目中的Jason格式的数据集打开后似乎看起来有点问题，为什么我看到的是三行这样的代码
```
version https://git-lfs.github.com/spec/v1
oid sha256:2b3a4f0e9ee84bfe99be621182f1e8de0d4bd3f7ed9bfa299ede0b4ad75912c4
size 37198185
```

**Comment by zfj1998** [comment]
These datasets were uploaded using Git LFS. I believe they should be downloaded using LFS, too.

**Comment by shaoyuyoung** [comment]
> These datasets were uploaded using Git LFS. I believe they should be downloaded using LFS, too.

Thank you
